export enum CustomerIdentityType {
    ID_CARD_9D = "ID_CARD_9D",
    ID_CARD_12D = "ID_CARD_12D",
    PASSPORT = "PASSPORT",
    BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE",
    BUSINESS_REGISTRATION_CERTIFICATE = "BUSINESS_REGISTRATION_CERTIFICATE",
    DRIVER_LICENSE = "DRIVER_LICENSE",
    PERMANENT_RESIDENT_CARD = "PERMANENT_RESIDENT_CARD",
    MILITARY_ID_CARD = "MILITARY_ID_CARD",
    POLICE_ID_CARD = "POLICE_ID_CARD",
    TEMPORARY_ID_CARD = "TEMPORARY_ID_CARD",
    VISA = "VISA", SWIFT_CODE = "SWIFT_CODE",
    INVESTMENT_REGISTRATION_CERTIFICATE = "INVESTMENT_REGISTRATION_CERTIFICATE",
    OTHER = "OTHER"
}