#Logging
logging.config: classpath:logback-test.xml
server.port: 7777
spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${JDBC_DRIVER_CLASS:org.h2.Driver}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 2 # Adjust as needed
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: test_pool
  h2:
    console:
      enabled: true
      path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: ${LIQUIBASE_TEST_CHANGELOG:classpath:db/changelog/sql-changelog.xml}
    drop-first: false
    enabled: true
    contexts: development
tech:
  corefinance:
    app:
      converter:
        local-date-to-string: true
        local-date-time-to-string: true
        zoned-date-time-to-string: true
        zoned-date-time-to-local-date-time: true
        zoned-date-time-to-date: true
      userprofile:
        common-user-service: true
        common-role-service: true
    common:
      filter-ordered:
        authen-filter: 2
        tenant-id-filter-order: 3
        trace-info-id-order: 0
        encoding-response-order: 100
      enabled:
        async: true
        simple-version: true
        property-encryption: true
        auto-response-encoding: true
        trace-id-filter: true
        tenant: true
      default-response-charset: utf-8
    log:
      enabled:
        services: true
        repositories: true
        api: true
      exclude-classes: "feign.Target"
    security:
      internal-api-key: No-key
      # Json Web Token
      jwt:
        expiration: 3600
        login-mode: SINGLE_LOGIN_PER_APP
        enabled:
          common: true
          cached: false
      public-key: classpath:public_key.der
      private-key: classpath:private_key.der
      no-authen-urls:
        - /
        - /void
        - /parserConfigurationException
        - /throwable
        - /test/api/*
      permission:
        default-control: ALLOWED
      authorize-check: true
      scan-controllers-actions: true
      ignore-controller-scan:
        - .springframework.
        - .springdoc.
        - .test.
      url-cors:
        cors-configurations:
          - url-pattern: /v3/api-docs/*
            allowed-origins:
              - http://localhost:4200
            allowed-methods:
              - GET
            allowed-headers: '*'
          - url-pattern: /**
            allowed-origins:
              - http://localhost:4200
              - http://*.corefinance.tech
            allowed-methods:
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - POST
              - PATCH
            allowed-headers: '*'
    encryption:
      plain: test
      encoded: ENC(O5MFWIMMOz+V3iItOVY60g==)
    initial:
      name-separator: _
      version-separator: .
      data-regex:
        permission:
          file-name-regex: classpath:initial/*permissions*.json
          replace-if-existed: true
        internal-api:
          file-name-regex: classpath:initial/*internal_api*.json
          replace-if-existed: true
export:
  format:
    date: yyyy/MM/dd
    datetime: yyyy/MM/dd HH:mm:ss
jasypt:
  encryptor:
    password: password
    # algorithm: PBEWithHmacSHA512AndAES_256
    algorithm: PBEWithMD5AndDES
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    # provider-class-name: com.sun.crypto.provider.SunJCE
    provider-name: SunJCE
    string-output-type: base64
    key-obtention-iterations: 1000
    pool-size: 1
