package tech.corefinance.product.common.enums;

public enum LoanFeePaymentType {
    FLAT, LOAN_AMOUNT_PERCENTAGE, REPAYMENT_PRINCIPAL_AMOUNT_PERCENTAGE, FLAT_NUMBER_OF_INSTALLMENTS,
    LOAN_AMOUNT_PERCENTAGE_NUMBER_OF_INSTALLMENTS
}
