package tech.corefinance.customer.enums;

public enum CustomerIdentityType {
    ID_CARD_9D, ID_CARD_12D, PASSPORT, BIRTH_CERTIFICATE, BUSINESS_REGISTRATION_CERTIFICATE, DRIVER_LICENSE,
    PERMANENT_RESIDENT_CARD, MILITARY_ID_CARD, POLICE_ID_CARD, TEMPORARY_ID_CARD, VISA, SWIFT_CODE,
    INVESTMENT_REGISTRATION_CERTIFICATE, OTHER
}
